Repository knative-extensions/knobots, pull requests merged in 2020-10, with the labels that each got.

#1 Add the nightly update workflow to knative-automation
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/L

#2 Fix team name, adjust email address.
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/XS

#3 Drop the plus
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/XS

#4 Enable the knative-automation cron
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/XS

#5 Add the auto-update jobs
  .github/workflows/auto-updates.yaml
  README.md
  actions-exclude.yaml
  deps-exclude.yaml
  gotool-exclude.yaml
  misspell-exclude.yaml
  prettier-exclude.yaml
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XL

#6 Fix email and slack settings
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/M

#11 add missing event-* repos
  repos.yaml
Labels: approved, cla: yes, lgtm, size/M

#12 Drop the pr-notify option.
  .github/workflows/auto-updates.yaml
  README.md
  repos.yaml
Labels: approved, cla: yes, lgtm, size/S

#14 adding release version and reason to update script
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/M
