Repository knative-extensions/knobots, pull requests merged in 2021-09, with the labels that each got.

#104 Adding Kafka Channel CRD Download
  .github/workflows/update-nightlies.yaml
Labels: cla: yes, approved, lgtm, size/XS

#101 Align Go version with 1.16
  .github/workflows/auto-fork.yaml
  .github/workflows/update-nightlies.yaml
Labels: cla: yes, approved, lgtm, size/XS

#103 Add eventing-kogito to knobots
  repos.yaml
Labels: cla: yes, approved, lgtm, size/XS

#96 Add kn-plugin-func to knobots
  repos.yaml
Labels: cla: yes, approved, lgtm, size/XS

#105 drop actions on mattmoor org
  community-exclude.yaml
  repos.yaml
Labels: cla: yes, approved, lgtm, size/S

#106 Add client's homebrew repositories
  actions-exclude.yaml
  deps-exclude.yaml
  gotool-exclude.yaml
  repos.yaml
Labels: cla: yes, approved, lgtm, size/S

#107 Add client-pkg repository
  repos.yaml
Labels: cla: yes, approved, lgtm, size/XS

#110 Disable kn-plugin-func dependencies
  deps-exclude.yaml
Labels: cla: yes, approved, lgtm, size/XS

#109 fix exclusions
  .github/workflows/auto-update-community.yaml
  .github/workflows/auto-update-markdown.yaml
  .github/workflows/auto-update-misspell.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  repos.yaml
Labels: cla: yes, approved, lgtm, size/XS

#111 fix jq command so omit works as expected
  actions/update-actions/entrypoint.sh
Labels: cla: yes, approved, lgtm, size/XS

#114 Add documentation on Knobots
  README.md
Labels: cla: yes, approved, lgtm, size/M

#113 Fix source auto-apply.yaml shortnames for matrix.
  actions/update-community/auto-apply.yaml
  actions/update-markdown/auto-apply.yaml
  actions/update-misspell/auto-apply.yaml
Labels: cla: yes, approved, lgtm, size/XS

#112 Adding COC doc for all knative repos
  actions/update-community/entrypoint.sh
Labels: cla: yes, approved, lgtm, kind/enhancement, size/S

#115 Typo fix
  cmd/gen-actions/main.go
Labels: cla: yes, approved, lgtm, size/XS

#116 Fixing typo in coc script
  actions/update-community/entrypoint.sh
Labels: cla: yes, approved, lgtm, size/XS, kind/bug

#117 Update to prepare for release 0.27
  actions/update-deps/action.yaml
Labels: cla: yes, approved, lgtm, size/XS

#118 Revert "adding COC doc for all knative repos (#112)"
  actions/update-community/entrypoint.sh
Labels: cla: yes, approved, lgtm, size/S
