Repository knative-extensions/knobots, pull requests merged in 2021-02, with the labels that each got.

#42 Don't notify #ggcr or #ko Slack channels
  repos.yaml
Labels: approved, cla: yes, kind/removal, lgtm, ok-to-test, size/XS

#45 Disable slack notifications for PRs, leave failures
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/M

#44 Add knative-sandbox/kn-plugin-sample to config
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#47 Add CODEOWNERS file for approvals
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS

#50 Add kn-plugin-admin and kn-plugin-source-kafka to config
  repos.yaml
Labels: cla: yes, lgtm, size/S

#52 fix token string
  .github/workflows/auto-fork.yaml
Labels: cla: yes, lgtm, size/XS

#54 Fix go get in auto-fork action
  .github/workflows/auto-fork.yaml
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#49 Switch knobots to 0.22 for next release
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS

#48 Exclude go-containerregistry from actions sync
  actions-exclude.yaml
Labels: approved, cla: yes, lgtm, size/XS

#46 Added control protocol repo
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS
