Repository knative-extensions/knobots, pull requests merged in 2021-05, with the labels that each got.

#80 Fix file permissions in docker actions.
  actions/update-actions/entrypoint.sh
  actions/update-community/entrypoint.sh
  actions/update-deps/entrypoint.sh
  actions/update-gofmt/entrypoint.sh
  actions/update-markdown/entrypoint.sh
  actions/update-misspell/entrypoint.sh
Labels: approved, cla: yes, lgtm, size/S

#81 Add jq command to update-actions
  actions/update-actions/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#83 Opt out google/ko and google/go-containerregistry
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#84 Remove unnecessary `$` in update actions
  cmd/gen-actions/actions_template.yaml
Labels: approved, cla: yes, lgtm, size/XS

#85 Remove extra `$` in all template
  .github/workflows/auto-update-actions.yaml
  .github/workflows/auto-update-community.yaml
  .github/workflows/auto-update-deps.yaml
  .github/workflows/auto-update-gofmt.yaml
  .github/workflows/auto-update-markdown.yaml
  .github/workflows/auto-update-misspell.yaml
Labels: approved, cla: yes, lgtm, size/S

#87 Bump to 0.24
  actions/update-deps/action.yaml
Labels: approved, cla: yes, lgtm, size/XS

#86 Fix update-community and add logging
  actions/update-community/action.yaml
  actions/update-community/entrypoint.sh
Labels: approved, cla: yes, kind/bug, lgtm, size/XS

#88 Remove CODEOWNERS
  .github/CODEOWNERS
Labels: approved, cla: yes, lgtm, size/XS
