Repository knative-extensions/knobots, pull requests merged in 2021-03, with the labels that each got.

#56 Fix CODEOWNERS by collapsing all teams to a single line
  .github/CODEOWNERS
Labels: cla: yes, size/XS

#55 Remove kn-plugin-* for Markdown prettifier PRs
  prettier-exclude.yaml
Labels: approved, cla: yes, lgtm, size/XS

#57 add kn-plugin-* configs for knobots
  repos.yaml
Labels: approved, cla: yes, lgtm, size/S

#59 Ignore spurious misspell complaint
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS

#58 Auto-manage website for update-codegen in particular.
  repos.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#62 Allow opt-out of syncing certain actions
  .github/workflows/auto-updates.yaml
  actions-omitted.yaml
Labels: approved, cla: yes, lgtm, size/S

#63 Add the knobots repo for configuration
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/S

#64 Load yaml2json before calling it
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS

#43 Add update nightly config for eventing-kafka-broker
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/M

#61 add kn-plugin-event
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#21 Add kperf to the repo list
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#65 Skip markdown formatting for website
  prettier-exclude.yaml
Labels: approved, cla: yes, lgtm, size/XS

#60 Add sync of files from knative/community
  .github/workflows/auto-updates.yaml
  community-exclude.yaml
Labels: approved, cla: yes, kind/enhancement, lgtm, size/L

#66 Fix bad indentation
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/S

#67 Fix repo path in update-community action
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS
