Repository knative-extensions/knobots, pull requests merged in 2021-01, with the labels that each got.

#25 Added reconciler-test to the synced repos
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#26 Disable notifications to knative-gcp channel
  repos.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS

#30 Include specific details about module changes
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/M

#31 Skip nightly release PR if there are no code changes
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/S

#32 future proof ref lookup
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/XS

#33 Include a log when bumping nightlies
  .github/workflows/auto-updates.yaml
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/M

#34 Update deps
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS

#28 Add forky
  .github/workflows/auto-fork.yaml
  hack/auto-fork.sh
Labels: approved, cla: yes, kind/enhancement, lgtm, ok-to-test, size/L

#37 Fix and simplify branch defaulting behavior
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/S
