Repository knative-extensions/knobots, pull requests merged in 2021-12, with the labels that each got.

#145 Add net-gateway-api to update-nightlies.yaml
  .github/workflows/update-nightlies.yaml
Labels: cla: yes, approved, lgtm, size/S

#146 use go install
  actions/update-deps/Dockerfile
Labels: cla: yes, approved, lgtm, size/XS

#148 Remove website repo from automation
  repos.yaml
Labels: approved, lgtm, size/XS

#149 Update to release 1.2/0.29
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS
