Repository knative-extensions/knobots, pull requests merged in 2021-04, with the labels that each got.

#68 Add net-ingressv2 to the repo list
  repos.yaml
Labels: approved, cla: yes, lgtm, size/XS

#69 Add a flag to force deps PRs for release
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/S

#70 Fix #69 syntax errors, simplify
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/S

#71 Fix `github.events` to `github.event`
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS

#72 Bump release family to 0.23 after 0.22 release
  .github/workflows/auto-updates.yaml
Labels: approved, cla: yes, lgtm, size/XS

#73 enable verbose logging temporarily for nightly release bump job
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/XS

#74 drop verbose logging and add some pipefail guards
  .github/workflows/update-nightlies.yaml
Labels: approved, cla: yes, lgtm, size/XS

#75 Split auto-updates into separate actions, generate workflow/fanout boilerplate
  .github/workflows/auto-update-actions.yaml
  .github/workflows/auto-update-community.yaml
  .github/workflows/auto-update-deps.yaml
  .github/workflows/auto-update-gofmt.yaml
  .github/workflows/auto-update-markdown.yaml
  .github/workflows/auto-update-misspell.yaml
  .github/workflows/auto-updates.yaml
  actions/calculate-matrix/Dockerfile
  actions/calculate-matrix/action.yaml
  actions/calculate-matrix/entrypoint.sh
  actions/update-actions/Dockerfile
  actions/update-actions/action.yaml
  actions/update-actions/auto-apply.yaml
  actions/update-actions/entrypoint.sh
  actions/update-community/Dockerfile
  actions/update-community/action.yaml
  actions/update-community/auto-apply.yaml
  actions/update-community/entrypoint.sh
  actions/update-deps/Dockerfile
  actions/update-deps/action.yaml
  actions/update-deps/auto-apply.yaml
  actions/update-deps/entrypoint.sh
  actions/update-gofmt/Dockerfile
  actions/update-gofmt/action.yaml
  actions/update-gofmt/auto-apply.yaml
  actions/update-gofmt/entrypoint.sh
  actions/update-markdown/Dockerfile
  actions/update-markdown/action.yaml
  actions/update-markdown/auto-apply.yaml
  actions/update-markdown/entrypoint.sh
  actions/update-misspell/Dockerfile
  actions/update-misspell/action.yaml
  actions/update-misspell/auto-apply.yaml
  actions/update-misspell/entrypoint.sh
  cmd/gen-actions/actions_template.yaml
  cmd/gen-actions/main.go
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XXL

#76 Copy OWNERS_ALIASES from knative/community; fill in OWNERS files
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L

#78 remove EN server
  repos.yaml
Labels: approved, cla: yes, kind/cleanup, lgtm, size/XS
