Repository knative-extensions/knobots, pull requests merged in 2021-10, with the labels that each got.

#108 Fix Eventing nightly updates for eventing-kafka-broker
  .github/workflows/update-nightlies.yaml
Labels: cla: yes, approved, lgtm, size/XS, kind/bug

#119 Rename net-ingressv2 to net-gateway-api
  repos.yaml
Labels: cla: yes, approved, lgtm, size/XS

#120 Add KafkaSource to eventing-kafka-broker nightly update
  .github/workflows/update-nightlies.yaml
Labels: cla: yes, approved, lgtm, size/XS

#123 Reformat Golang code after action update in one PR
  actions/update-actions/Dockerfile
  actions/update-actions/entrypoint.sh
Labels: cla: yes, approved, lgtm, size/S

#125 Move into repo-to-change before applying gofmt
  actions/update-actions/entrypoint.sh
Labels: cla: yes, approved, lgtm, size/XS

#126 Move all update actions to 1.17
  actions/calculate-matrix/Dockerfile
  actions/update-deps/Dockerfile
  actions/update-gofmt/Dockerfile
  actions/update-misspell/Dockerfile
Labels: cla: yes, approved, lgtm, size/XS

#130 Add nightly builds of eventing CRDs to rabbitmq
  .github/workflows/update-nightlies.yaml
Labels: cla: yes, approved, lgtm, size/S
