Repository knative-extensions/knobots, pull requests merged in 2022-08, with the labels that each got.

#219 Remove releasability action from some repos
  actions-omitted.yaml
Labels: approved, lgtm, size/S

#220 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#221 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#222 Add Security Guard Repo
  repos.yaml
Labels: approved, lgtm, size/XS

#223 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#224 Update releasability for 1.7
  workflow-templates/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#225 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#229 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#226 security-guard omit knative-releasability
  actions-omitted.yaml
Labels: approved, lgtm, size/XS

#227 Adding a step to omit releasability for a new repo
  README.md
Labels: approved, lgtm, size/S

#207 chore: Set permissions for GitHub actions
  .github/workflows/auto-fork.yaml
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS

#230 bump version to 1.8
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#231 chore: knative-sandbox/func-tastic in repos.yaml
  repos.yaml
Labels: approved, lgtm, size/S
