Repository knative-extensions/knobots, pull requests merged in 2022-07, with the labels that each got.

#212 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#213 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#216 Bump update-deps to next release version
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#217 bump to go1.18
  actions/calculate-matrix/Dockerfile
  actions/update-actions/Dockerfile
  actions/update-deps/Dockerfile
  actions/update-gofmt/Dockerfile
  actions/update-misspell/Dockerfile
Labels: approved, lgtm, size/S

#218 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
