Repository knative-extensions/knobots, pull requests merged in 2022-03, with the labels that each got.

#155 Fix reconciler-test assignees
  repos.yaml
Labels: approved, lgtm, size/XS

#156 Replace channel-wg-leads and source-wg-leads by eventing-writers
  repos.yaml
Labels: approved, lgtm, size/M

#157 include productivity repos to get OWNER updates
  actions-exclude.yaml
  deps-exclude.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  misspell-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/S

#158 bump update deps action to next version
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#159 Fix the config for actions and actions-downstream-test repos
  repos.yaml
Labels: approved, lgtm, size/XS

#160 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: approved, lgtm, size/XS

#161 include Infra repo to get OWNER updates
  actions-exclude.yaml
  deps-exclude.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  misspell-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/S

#162 include Knobots to get OWNER updates
  actions-exclude.yaml
  deps-exclude.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  misspell-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/S

#163 [main] Update community files
  OWNERS_ALIASES
Labels: approved, size/L, lgtm
