Repository knative-extensions/knobots, pull requests merged in 2022-10, with the labels that each got.

#240 [chore] Preparing for func to be moved to knative org
  repos.yaml
Labels: approved, lgtm, kind/cleanup, size/S

#241 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#242 Update releasability for 1.8
  workflow-templates/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#243 Drop detail log in PR body
  .github/workflows/auto-update-deps.yaml
Labels: approved, lgtm, size/XS
