Repository knative-extensions/knobots, pull requests merged in 2022-04, with the labels that each got.

#164 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/S

#166 pay tech debt
  .github/workflows/auto-update-deps.yaml
  actions/calculate-matrix/Dockerfile
  actions/calculate-matrix/entrypoint.sh
  actions/update-actions/Dockerfile
  actions/update-deps/action.yaml
  actions/update-deps/auto-apply.yaml
  actions/update-gofmt/Dockerfile
  actions/update-misspell/Dockerfile
Labels: approved, lgtm, size/M

#168 Update workflows
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-releasability.yaml
  workflow-templates/knative-release-notes.yaml
  workflow-templates/knative-security.yaml
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, size/L, lgtm

#169 fix nightly releases that use app.kubernetes.io/version annotation
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/S

#170 bake next release version into workflow template
  workflow-templates/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#180 [main] Update community files
  OWNERS_ALIASES
Labels: approved, lgtm, size/XS

#181 Enable auto-merge for update-community PRs and small cleanups
  .github/workflows/auto-update-actions.yaml
  .github/workflows/auto-update-community.yaml
  .github/workflows/auto-update-deps.yaml
  .github/workflows/auto-update-gofmt.yaml
  .github/workflows/auto-update-markdown.yaml
  .github/workflows/auto-update-misspell.yaml
  actions/update-actions/action.yaml
  actions/update-actions/entrypoint.sh
  actions/update-community/action.yaml
  actions/update-community/entrypoint.sh
  actions/update-deps/action.yaml
  actions/update-deps/entrypoint.sh
  actions/update-gofmt/action.yaml
  actions/update-gofmt/entrypoint.sh
  actions/update-markdown/action.yaml
  actions/update-markdown/entrypoint.sh
  actions/update-misspell/action.yaml
  actions/update-misspell/entrypoint.sh
  cmd/gen-actions/actions_template.yaml
Labels: approved, lgtm, size/M

#182 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#183 OWNER_ALIASES in knative/community are in a different location now
  actions/update-community/action.yaml
  actions/update-community/entrypoint.sh
Labels: approved, lgtm, size/XS

#184 bump actions
  .github/workflows/auto-update-actions.yaml
  .github/workflows/auto-update-community.yaml
  .github/workflows/auto-update-deps.yaml
  .github/workflows/auto-update-gofmt.yaml
  .github/workflows/auto-update-markdown.yaml
  .github/workflows/auto-update-misspell.yaml
  cmd/gen-actions/actions_template.yaml
Labels: approved, lgtm, size/M

#185 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#186 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#187 Remove eventing-awssqs
  repos.yaml
Labels: approved, lgtm, size/XS

#188 default inputs on scheduled runs
  workflow-templates/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#189 Run knative-go-test action on main branch
  workflow-templates/knative-go-test.yaml
Labels: approved, lgtm, size/XS

#190 Update after release 1.4
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS
