Repository knative-extensions/knobots, pull requests merged in 2022-05, with the labels that each got.

#192 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#193 drop downstream test repo
  actions-exclude.yaml
  deps-exclude.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  misspell-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/S

#194 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#195 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#196 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#197 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#199 fix: Markdown formatter does not create pr
  actions/update-markdown/entrypoint.sh
Labels: approved, lgtm, size/XS

#200 Enable spellcheck for Infra
  misspell-exclude.yaml
Labels: approved, lgtm, size/XS

#201 Search for files AFTER cd into main
  actions/update-markdown/entrypoint.sh
Labels: approved, lgtm, size/XS

#202 Update releasability defaults for 1.5
  workflow-templates/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#203 update-actions-skip-review
  actions/update-actions/entrypoint.sh
Labels: approved, lgtm, size/XS
