Repository knative-extensions/knobots, pull requests merged in 2023-09, with the labels that each got.

#326 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#327 Bump go to 1.21
  .github/workflows/update-nightlies.yaml
  actions/calculate-matrix/Dockerfile
  actions/update-actions/Dockerfile
  actions/update-deps/Dockerfile
  actions/update-gofmt/Dockerfile
  actions/update-misspell/Dockerfile
Labels: approved, lgtm, size/S

#328 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#331 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#332 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#333 Add the repo serving-progressive-rollout
  repos.yaml
Labels: approved, lgtm, size/XS

#334 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#335 Added UX WG to automation
  actions-exclude.yaml
  deps-exclude.yaml
  gofmt-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/XS

#337 Disable autosyncing style and use manual one
  actions-omitted.yaml
Labels: approved, lgtm, size/XS
