Repository knative-extensions/knobots, pull requests merged in 2023-10, with the labels that each got.

#338 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#339 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#341 :lady_beetle: Open PR on any change in vendorless projects
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS, kind/bug

#343 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#344 added net-gateway-api gateway-api.yaml crd file to nightlies
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#345 Bump update-deps to next release version
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS
