Repository knative-extensions/knobots, pull requests merged in 2023-05, with the labels that each got.

#300 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#301 Revert "force update deps during release time (#297)"
  .github/workflows/auto-update-deps.yaml
  actions/update-deps/auto-apply.yaml
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#302 Make go version consistent with actions
  actions/update-gofmt/Dockerfile
Labels: approved, lgtm, size/XS

#303 Include knative/hack repo for GH actions
  README.md
  actions-exclude.yaml
  actions-omitted.yaml
Labels: approved, lgtm, size/S

#304 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#305 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#306 drop archived repos
  repos.yaml
Labels: approved, lgtm, size/S
