Repository knative-extensions/knobots, pull requests merged in 2023-02, with the labels that each got.

#260 Update deps for v1.10
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#261 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#262 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#263 Change permission for Parent git dir
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/S

#266 Fix unsafe git dir error
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/S

#267 Updates assignees for networking repos
  repos.yaml
Labels: approved, lgtm, size/S

#269 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#270 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#271 update serving teams
  .github/workflows/update-nightlies.yaml
  repos.yaml
Labels: approved, lgtm, size/S

#272 drop external orgs
  community-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/S
