Repository knative-extensions/knobots, pull requests merged in 2023-06, with the labels that each got.

#307 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#308 Remove archived knative-sandbox/control-protocol repository
  repos.yaml
Labels: approved, lgtm, size/XS

#309 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#310 Add job to sync eventing & EKB latest to eventing-istio
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/S

#312 Use knative-sandbox teams for sandbox repos as assignees
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS

#314 excluding vendor and third_party at all the level in multimodule setup in update-gofmt
  actions/update-gofmt/entrypoint.sh
Labels: approved, lgtm, size/XS, kind/bug

#315 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
