Repository knative-extensions/knobots, pull requests merged in 2023-03, with the labels that each got.

#273 Add eventing-istio to repositories
  repos.yaml
Labels: approved, lgtm, size/XS

#274 Add Git submodules to safe directories
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#276 [main] Update community files
  OWNERS_ALIASES
Labels: skip-review

#279 Use full path for submodule safe dir
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#281 default channel is in upstream action
  workflow-templates/knative-releasability.yaml
Labels: approved, lgtm, size/XS

#282 :broom: Extract tools to knative.dev/toolbox
  .github/workflows/auto-fork.yaml
  actions/update-deps/Dockerfile
Labels: approved, lgtm, size/XS, kind/cleanup

#283 update slack channels
  repos.yaml
Labels: approved, size/L, lgtm

#277 [WIP]: Switch to `GITHUB_OUTPUT` env var instead of using deprecated `set-output`
  .github/workflows/auto-update-actions.yaml
  .github/workflows/auto-update-community.yaml
  .github/workflows/auto-update-deps.yaml
  .github/workflows/auto-update-gofmt.yaml
  .github/workflows/auto-update-markdown.yaml
  .github/workflows/auto-update-misspell.yaml
  .github/workflows/update-nightlies.yaml
  actions/calculate-matrix/entrypoint.sh
  actions/update-actions/entrypoint.sh
  actions/update-community/entrypoint.sh
  actions/update-deps/entrypoint.sh
  actions/update-gofmt/entrypoint.sh
  actions/update-markdown/entrypoint.sh
  actions/update-misspell/entrypoint.sh
  cmd/gen-actions/actions_template.yaml
Labels: approved, lgtm, kind/cleanup, size/M
