Repository knative-extensions/knobots, pull requests merged in 2023-04, with the labels that each got.

#284 Remove job to copy eventing-kafka nightlies to eventing-kafka-broker repo
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#286 fix markdown task
  actions/update-markdown/entrypoint.sh
Labels: approved, lgtm, size/S

#287 Remove eventing-couchdb
  repos.yaml
Labels: approved, lgtm, size/XS

#288 remove old workflows
  actions/update-actions/entrypoint.sh
Labels: approved, lgtm, size/S

#290 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#291 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#289 infer the golang module version from the release version
  actions/update-deps/action.yaml
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#292 fix formatting
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/S

#293 drop per repo release note job
  actions/update-actions/entrypoint.sh
  workflow-templates/knative-release-notes.yaml
Labels: approved, lgtm, size/M

#294 drop module release input
  .github/workflows/auto-update-deps.yaml
  actions/update-deps/auto-apply.yaml
Labels: approved, lgtm, size/XS

#295 my bash is bad
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS

#296 fix module name
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS

#297 force update deps during release time
  .github/workflows/auto-update-deps.yaml
  actions/update-deps/auto-apply.yaml
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#298 Update RELEASE to upcoming release version
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#299 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
