Repository knative-extensions/knobots, pull requests merged in 2023-08, with the labels that each got.

#320 HoldTillRename: Rename knative-sandbox to knative-extensions
  .github/workflows/auto-fork.yaml
  .github/workflows/auto-update-actions.yaml
  .github/workflows/update-nightlies.yaml
  OWNERS_ALIASES
  README.md
  actions-exclude.yaml
  actions/update-actions/auto-apply.yaml
  actions/update-actions/entrypoint.sh
  actions/update-community/entrypoint.sh
  actions/update-deps/entrypoint.sh
  actions/update-gofmt/entrypoint.sh
  actions/update-markdown/entrypoint.sh
  actions/update-misspell/entrypoint.sh
  deps-exclude.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  misspell-exclude.yaml
  repos.yaml
  workflow-templates/knative-go-build.yaml
  workflow-templates/knative-go-test.yaml
  workflow-templates/knative-security.yaml
  workflow-templates/knative-stale.yaml
  workflow-templates/knative-style.yaml
  workflow-templates/knative-verify.yaml
Labels: approved, size/L, lgtm

#321 Bump update-deps to next release version
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#322 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#323 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#324 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#325 Update Go version in Dockerfiles to align with rest
  actions/calculate-matrix/Dockerfile
  actions/update-actions/Dockerfile
  actions/update-deps/Dockerfile
  actions/update-misspell/Dockerfile
Labels: approved, lgtm, size/XS
