Repository knative-extensions/knobots, pull requests merged in 2024-03, with the labels that each got.

#369 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#370 Update create-pull-request actions
  cmd/gen-actions/actions_template.yaml
Labels: approved, lgtm, size/XS

#372 Add contour-gateway yaml to nightly
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS

#373 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#374 Add eventing-rabbitmq integration back
  repos.yaml
Labels: approved, lgtm, size/XS

#375 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#376 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#353 Add specs repo to knobots
  actions-exclude.yaml
  deps-exclude.yaml
  gofmt-exclude.yaml
  markdown-exclude.yaml
  misspell-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/XS, kind/cleanup

#377 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#378 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
