Repository knative-extensions/knobots, pull requests merged in 2024-02, with the labels that each got.

#360 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#361 Remove eventing-kafka
  repos.yaml
Labels: approved, lgtm, size/XS

#362 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#363 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#364 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#365 Add func-go to repository config
  repos.yaml
Labels: approved, lgtm, size/XS

#366 drop machinery for net-http01
  repos.yaml
Labels: approved, lgtm, size/XS

#367 drop machinery for eventing-rabbitmq
  repos.yaml
Labels: approved, lgtm, size/XS

#368 bump go to v1.22
  .github/workflows/auto-fork.yaml
  .github/workflows/update-nightlies.yaml
  actions/calculate-matrix/Dockerfile
  actions/update-actions/Dockerfile
  actions/update-deps/Dockerfile
  actions/update-gofmt/Dockerfile
  actions/update-misspell/Dockerfile
Labels: approved, lgtm, size/S
