Repository knative-extensions/knobots, pull requests merged in 2024-09, with the labels that each got.

#403 Enable debugging for update deps action entrypoint script
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#404 Revert "Enable debugging for update deps action entrypoint script (#4…
  actions/update-deps/entrypoint.sh
Labels: approved, lgtm, size/XS

#405 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#407 Create target dir if it does not exist in update-nightlies
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/XS

#409 Update Eventing manifest nightlies for Backstage plugins repo
  .github/workflows/update-nightlies.yaml
Labels: approved, lgtm, size/S

#383 Adding func-python to the repo list of automation
  deps-exclude.yaml
  gofmt-exclude.yaml
  repos.yaml
Labels: approved, lgtm, size/XS
