Repository knative-extensions/knobots, pull requests merged in 2025-01, with the labels that each got.

#421 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#422 Install envsubst in update-deps image
  actions/update-deps/Dockerfile
Labels: approved, lgtm, size/XS

#423 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#424 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#425 Update next release version to 1.18
  actions/update-deps/action.yaml
Labels: approved, lgtm, size/XS

#426 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
